### ISSUE TITLE
Add "mcs" to the list of compilers recognized by our configure process

### ISSUE THREAD

**Issue by alex-ter** [tomboy-notes/tomboy#10]
~~Fedora 24 (at least) does not have `gmcs` or `dmcs` having `mcs` instead. Let's add the respective option into configure in.~~

EDIT after @descriptor's comment below: we actually want to stop using dmcs and gmcs completely and only use mcs, as the former two are very old and not used these days (but still exist in some distros as wrapper scripts for backwards compatibility/easier migration).

**Comment by decriptor** [comment]
You should completely get rid of gmcs and dmcs. They should just not be supported (very old) and only support mcs (and csc?)

**Comment by alex-ter** [comment]
Indeed (did some reading on those various versions), thanks Stephen. Corrected the title
