### ISSUE TITLE
Feature request: new note added to Notebook when Notebook is selected

### ISSUE THREAD

**Issue by Alex-CodeLab** [tomboy-notes/tomboy#107]
issue:
Currently, after selecting a Notebook, `ctrl-N` creates a new Note, but it is not added to the notebook.

Same for creating a new Note using the `Link` button: the new Note is not added to the same Notebook, and it takes some manual clicking/navigation to add every individual note to the Notebook.

request: 
- automatically add _new_ Notes to the currently selected Notebook (if a notebook is selected)
- new notes are automatically added to the same Notebook as the 'parent' Note

**Comment by davidbannon** [comment]
Yes, Alex, I think that should be case and is, probably, pretty easy to implement. Look for it in next release.

Thanks for your request !

David

**Comment by davidbannon** [comment]
Ah, sorry Alex. I thought this request was in tomboy-ng.

No one is putting any time into Tomboy anymore I am afraid. I am pretty sure its not going to happen there. 

I can and will add this feature to -ng, maybe its time you considered moving over there ?

David

**Comment by Alex-CodeLab** [comment]
ok thanks.

I tried ng, but it was not working on ubuntu 18.04, so I un-installed it. 
(unable to close the config dialog, and the actual app was never visible)

**Comment by davidbannon** [comment]
Alex, I personally use Ubuntu 18.04 as my dev platform.  Without any problems. 
I'd dearly like your help in getting to the bottom of your problem.
Which desktop do you use ?
David
