### ISSUE TITLE
Suggested Content for the Windows wiki page

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy#11]
Below is content suggested as suitable to replace that on https://wiki.gnome.org/Apps/Tomboy/Installing/Windows
Not sure what markup Gnome uses so have not attempted to embed the link that goes to another Gnome page. And note, we point to the Github Release page for Tomboy downloads rather than the Gnome page (which at present have outdated versions).
Enjoy !
David

# Instructions for installing a Tomboy Windows release

- The following instructions assume you are installing the current version of Tomboy on Windows 8 or Windows 10. See "Windows 7" further down if this is not the case. 
- Please be aware that Windows will be uncomfortable about the software you are installing, and you should take such warnings seriously. However, the developers and maintainers of Tomboy do believe its safe to proceed as long as you follow these instructions carefully. ![unknown_publisher](https://cloud.githubusercontent.com/assets/6291248/17967343/f91f369a-6b09-11e6-81ae-c122f24af4e2.png)

1.  Firstly, install the GTK+ libs from here: http://downloads.sourceforge.net/gtk-win/gtk2-runtime-2.24.10-2012-10-10-ash.exe?download . Accept the suggested defaults.
2.  Then install GTK# from here: http://www.mono-project.com/download/#download-win (Note you want "GTK# for .NET", *not* the 32 or 64-bit Mono package). Accept the suggested defaults.
3.  Install Tomboy from the Windows Installer (the msi file) at https://github.com/tomboy-notes/tomboy/releases/ _(this should be from the Gnome page once we have that process under control)_. Windows will need you to tell it to proceed with the install even though its from an Unknown Publisher. You will get a scary blue screen saying Windows has protected your PC, click "more" to see a "Run anyway" button.

![win_protected](https://cloud.githubusercontent.com/assets/6291248/17967373/2889df48-6b0a-11e6-88d7-49b2ab669943.png)
4.  You can now start Tomboy from the shortcut on your Desktop, that will put an icon on your System Tray (maybe look under "more apps"). You will see lots of things to do by Left or Right clicking that icon.
5. If you find Tomboy half as good as we expect, you will probably want to add the shortcut to the Startup List. Run -> shell:startup and drag a copy of the shortcut into the list area. 

## Windows 7 or Earlier
If you are using Windows 7 or earlier, then its likely you will have an older version of .NET than 4.0. See http://www.microsoft.com/en-us/download/details.aspx?id=17851 . Tomboy requires .NET 4.0 or greater.

## Upgrading
Upgrading - only requires steps 3 and 4 above unless your existing Tomboy is earlier than 1.3.2. If you have the earlier version, you should first remove it, your [[link to https://wiki.gnome.org/Apps/Tomboy/Directories]] notes will remain in place and its most likely your existing GTK+ and GTK# will be fine. 

## Debugging
If Tomboy does not start up as expected, try running from a command prompt and watch the messages that (should) appear.

**"C:\Program Files (x86)\Tomboy\Tomboy.exe" --debug**

If the messages indicate missing DLL files, again at the command prompt, type the command "path". The result should mention both GTK2 and GtkSharp, check they are there and that they point to somewhere that contains right looking files. If not, you may be best to remove Tomboy, GTK# and GTK+ and reinstall as above. And reboot. 
If that does not work, please log a bug report.

## Bugs ?
If something on this page does not work, or you don't understand it, thats a bug and we'd really like you to report it. Please consider telling us what operating system you are using, what goes wrong, maybe the results from your path command. https://github.com/tomboy-notes/tomboy/issues

-------------------------------------------------------
_The existing section headed "Importing notes from Linux" seems out of place here. If it belongs anywhere, its on the Directories page but it really does not say anything useful._

**Comment by alex-ter** [comment]
Thanks David, I've finally got editor permissions for the wiki and have updated the Downloads page already. Will update the installation instructions in the next couple of days - great work.

**Comment by GunArm** [comment]
Nice work.  This is barrett from the mailing list.  I'm curious why you recommend pinning it to the task bar, since it already resides in the task-tray by the clock?

**Comment by davidbannon** [comment]
Hmm, interesting. It did not appear in the tray after my install. (Win10 
Enterprise, a VM). I was quite surprised about that, major part of TB 
usefullness comes that way. Maybe I'll go and repeat the install, maybe 
I missed it ?  Running on a laptop (comfy chair, in sight of the wood 
heater) and need to slide around a bit to see the full Windows Desktop. 
Will get back to you.

Davo

**Comment by davidbannon** [comment]
Yep Barrett, I have not used Windows since, perhaps, 1998 and my 
ignorance shows !

My pinning was about getting a usable Tomboy icon available, what I 
needed to do is to get Tomboy into the System Tray. It gets there as a 
result of the user "Opening" the shortcut on every reboot OR adding the 
shortcut into the Startup group. Much tidier !

I'll alter that draft accordingly.

Thanks

David

**Comment by alex-ter** [comment]
Thanks everyone, I've updated the [downloads page](https://wiki.gnome.org/Apps/Tomboy/Installing/Windows) using your proposal, David as a base. The "importing" section I believe is useful for those who want to move notes over from a different machine without using sync (and yeah, mentioning Linux there was a bit misleading). I've slightly rearranged the text and add a couple of points like use of the `TOMBOY_PATH_PREFIX` variable, which may come in handy for some.
