### ISSUE TITLE
Reg:Cross-compilng

### ISSUE THREAD

**Issue by anantha-vidhya** [tomboy-notes/tomboy#117]
I want develop a navigation utility with sample maps in our am4378 arm processor based SBC Board. 
So i am searching for such kind of opensource.
Can i know is this one suitable for that if so can you please describe the steps to do this .
Thanks & Regards
A.N.V.Lavanya

**Comment by davidbannon** [comment]
Your question seems to have absolutely no connection to Tomboy Notes but try this https://wiki.lazarus.freepascal.org/LazMapViewer

Davo
