### ISSUE TITLE
Crash After Deleting A Note (bgo732196)

### ISSUE THREAD

**Issue by alex-ter** [tomboy-notes/tomboy#13]
This is a follow up for [bgo732196](https://bugzilla.gnome.org/show_bug.cgi?id=732196) as it seems to be still valid for 1.15.5. Below is the copy of the description and the most important pieces of the description and follow-up conversation:
#### Description
If I delete a note from the note itself, it takes a while to disappear from the Search All Notes window. If I click on the deleted note's name in that window before it disappears, Tomboy crashes (immediately quits).

#### Discussion and some summary
We've established that crash vs. "deleted note stays visible" may be caused by the way we've startedd Tomboy. Command-line crashes and the "usual" way through the shortcut tends to keep the note.

I was not able to reproduce the crash, but @davidbannon had is crashing on his VM, UbuntuMate 16.04.1.

In general, the main piece there - whether it crashes or not - is that the note should not stay seemingly alive after being deleted, whatever the deletion way was used (from Search All window or the Note window itself).

**Comment by davidbannon** [comment]
OK, here is a solution. I would not presume to turn it into a pull request just yet, I don't know my way around the code nor the culture sufficiently. But it does work and, honestly, does seem to me like its how it should be. Maybe I have overlooked something....

Add a call to UpdateResults (); to the function OnNotesDeleted () line #737 of RecentChanges.cs

As I said, works for me on Ubuntu.

David

**Comment by alex-ter** [comment]
Thanks for the proposal. I'll review/test it today or tomorrow.

**Comment by alex-ter** [comment]
Yes, this seems to be the solution, works fine for me and looks reasonable. I even recall I wanted to add that update there a while ago for a reason I no longer remember :)

@davidbannon, do you want to create a pull request for this, so that your contribution is fully represented in a git history? If you prefer me to create a patch, no problem with that too.
