### ISSUE TITLE
Addition to building instructions on wiki

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy#14]
https://wiki.gnome.org/Apps/Tomboy/Developers gives build instructions, one step of which (for Ubuntu) is to run 
`sudo apt-get build-dep tomboy`
That command requires access to src packages, unfortunately, in a new install of Ubuntu, the src repositories are disabled. I suggest we add a note before there suggesting the user enable at least one src repo. eg -
_On ubuntu, the package manager requires access to a source repository. If you have not already done so, you can enable this from the Control Center -> Software & Updates -> Ubuntu Software and tick "Source Code" or directly edit sources.list uncommenting an appropriate src line._

`sudo vi /etc/apt/sources.list`

Please comment.
David

**Comment by trepidity** [comment]
+1

**Comment by alex-ter** [comment]
Looks good to me as well. Let's sort out your wiki permissions, so that yoi can add it by yourself. As you've mentioned it still doesn't work for you, so I'll check it out today or tomorrow and get back to you.

**Comment by alex-ter** [comment]
Okay, as we've finally worked permissions out for you David and we have a consensus over the change (thanks @trepidity for your feedback!), feel free to get this change in.

**Comment by davidbannon** [comment]
OK, done that.

Reminder to self - next time we play with that page, replace 'username' with $USER in the commands to simplify things a bit.
