### ISSUE TITLE
Wiki - a page about backups

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy#15]
I think the Wiki needs a page about backups, it should have some advice about how to back up and maybe even mention the Backup directory down where our Notes are stored. As a long term user of Tomboy, I have always know there is a ~/Backup directory but I have no idea how files get there nor how to use it. 
I have always taken the view that a backup strategy that does not involve the occasional test recover is worthless ....
I use a cron driven script that tars up my whole notes directory from time to time. My notes exist on four different machines too but sync deletes as well as creates....
Maybe we need to hear what other users do ?
David

**Comment by alex-ter** [comment]
I think that would be helpful, yes. So anyone reading this - please share your backup strategy, if any, and we'll come up with a general roundup.

**Comment by levlaz** [comment]
I handle backups completely outside of Tomboy. I have Tomboy syncing to a local folder which is then synced to a personal Nextcloud instance. 

I then have my Nextcloud (both /data and the MySQL DB) being backed up to [Backblaze](https://www.backblaze.com/) each day. In this model Nextcloud is really the source of truth for the latest info about my notes. This works pretty well for me since I can restore this on any machine without too much trouble.

**Comment by alex-ter** [comment]
Thanks for sharing!

**Comment by nightwindzero** [comment]
I have a script that zips all my customized settings and ssh's them offsite.

**Comment by davidbannon** [comment]
# Draft Content Backup Page.
OK, you have some Tomboy notes. Its likely they are in some way, important to you. The more you use Tomboy, the more you need to ensure you have a backup strategy. Fact is, sooner or later you will need that backup, or, sadly, wish you had it !

Backup is about recovering from something bad, perhaps slippery fingers or a hardware failure. And remember, any backup strategy that is not tested in some way is worthless.

**Accidental Delete**
Now, Tomboy is already giving you some protection from an accidental delete. The deleted note is actually moved to a folder called, appropriately, 'backup' where your notes are stored. [[link to where are my notes]]. How about having a practice run ?  Make a dummy note, put some text in there and delete it. See if you can find the note, it won't be obvious from the file name. Linux users can grep for some text you remember was in the note. 
_Example grep command._ 
Windows uses can do what ?   
Try copying (not moving) that note back into the notes directory. 

Tomboy eventually really deletes 'deleted' notes, hmm, how long is 'eventually' ?

**Hardware Failure**
If you are syncing your notes to another system, then perhaps you think that is all the protection you need. Everything is copied to another box. But do consider how often backup happens, if its just occasionally, can you risk the material not yet transferred ? 

Another approach is to grab a copy of the note files and keep them somewhere. [[link to where are my notes]] shows where they are, nothing to stop you copying them right now. Trouble is, will you remember to do so ?  You also need to ensure you copy to  another box over the network, eg NFS or some Cloud system. Again, test such a setup, its too late to test when some emergency hits.

**Specific Working Examples**
Here are some suggestions by the very active Tomboy Community of how they make sure their notes are safe.   
.....
....

**Comment by alex-ter** [comment]
LGTM, I'd suggest to add a piece on how exactly one can test the backup without accidentally messing up notes, especially in the synchronized setup. Or at least add a warning so that people are careful. E.g. something like a clean VM install - may be an overkill, but is the safest way to do that.

> Windows uses can do what ?

Notepad++ has a "File Search" mode, other text editors certainly also do.

> Tomboy eventually really deletes 'deleted' notes, hmm, how long is 'eventually' ?

This is actually done immediately, the note is merely moved to the backup dir right away upon "Delete" operation. [Here's the code](https://github.com/tomboy-notes/tomboy/blob/master/Tomboy/NoteManager.cs#L436-L461).

**Comment by trepidity** [comment]
Which I believe is when the note loss can happen. There was an old bug in
something outside of tomboy that could cause this.

**Comment by davidbannon** [comment]
1. Yes Alex, I intend some step by step instructions. While I'll suggest a VM, I think that the average user probably needs a simpler solution. Step by step on how to build and then use an appropriate VM would be beyond scope and if the user already 'does' VMs they would be capable of doing the rest themselves, once pointed in right direction. I'd prefer some cli instructions for, at least the Linux user. I note that Windows10 now has an accessible command line too. Is it politically incorrect to go down that path ?
2. Hm, Notepad++, unless we have a full time windows user willing, I guess I'll have to play...
3. Looks like my text is not clear. To me, 'deleted' is moved to 'backup' and no longer visible. By "really deleted" I mean removed from even 'backup'. I thought (??) files so moved don't remain there forever, sounds like I am wrong ???

I note that a rival app has a "history" button that shows the user old, deleted notes. Could be a useful addition.......

David

**Comment by alex-ter** [comment]
Yeah, describing a VM setup is definitely way to much for such an instruction, so let's not focus on that, just like you propose.

I can prepare Notepad++ instructions/screenshots, however that's really very simple, file search is in the same UI window as the "usual" in-document search.

There's no removal from the backup, Tomboy does not do that on its own. Maybe some sort of a built-in viewer with a "delete this note forever" + "clean all" combination could be useful. As Tomboy does not keep any editing history in the note or elsewhere, the "history" option would really only be able to show what's currently kept in the backup folder anyway.

@trepidity, do you remember any details on that, bug number or that "outside of Tomboy" thing name, maybe?

**Comment by alex-ter** [comment]
@davidbannon, so David,do you plan to push this one out to wiki?

**Comment by davidbannon** [comment]
No Alex, it needs work before that !
Sorry, I have been traveling and, recently, a bit unwell. But its on my do do list.
David

**Comment by alex-ter** [comment]
Ok, no worries, just wanted to make sure :)

**Comment by davidbannon** [comment]
I reckon the block above is probably OK to go to the wiki now, been there for a while and I not seen any objections ....
It will still need some work done on the Windows side (and Mac, hope thats not just wishful thinking...).
??
David

**Comment by alex-ter** [comment]
Yes, I think it's good to go. Feel free to publish it, I'll then add Windows part similar to what you have for Linux. MacOS is an open problem, as there's still no one willing to help out and having access to a Mac. Let's add a section for that and invite contributions within it.

**Comment by davidbannon** [comment]
OK, moved that content to the Wiki. It still leaves Windows (and Mac) users dangling. Hoping someone who does use Windows might like to contribute.

**Comment by alex-ter** [comment]
Thanks David, if no one else chimes in with Windows version, I'll add it later. And for the MacOS one we'd need to wait for someone using Tomboy thete to add the content.

**Comment by trepidity** [comment]
Or for a working version of Tomboy on OS X

**Comment by alex-ter** [comment]
:smiley: oh yeah, unfortunately chances of anyone still using older Tomboy version on Mac are slim to none these days, AFAIU
