### ISSUE TITLE
[Ubuntu 14.04] Build failed due to no AX_REQUIRE_DEFINED macro available

### ISSUE THREAD

**Issue by grahateknik** [tomboy-notes/tomboy#26]
Hi.. I'm trying to build tomboy on my machine : Ubuntu 14.04 x84_84
I cloned the project and ran autogen.sh.
Then I found this error

*** WARNING: I am going to run 'configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** './autogen.sh' command line.

Copying file po/Makefile.in.in

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
libtomboy/Makefile.am:8: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
**./configure: line 3174: syntax error near unexpected token `YELP_HELP_INIT'
./configure: line 3174: `AX_REQUIRE_DEFINED(YELP_HELP_INIT)'**

Not sure if it's a bug. Can anybody help?

**Comment by alex-ter** [comment]
Looks like your system is missing yelp-tools package. Check out our wiki page on building on Linux  it lists preparational steps there: https://wiki.gnome.org/Apps/Tomboy/Developers

**Comment by grahateknik** [comment]
Hi Alex. I already have the required packages installed but I can't get past autogen.sh error message.
I did try using another machine with 14.04 64-bit and start over following compilation guide that you provided. I received different error:

aclocal: --install should copy macros in the directory indicated by the
aclocal: first -I option, but no -I was supplied.

**Comment by alex-ter** [comment]
That's strange - I've tested build on 16.04 and I think on 14.04 as well. Could you please post the full log from that second machine?

**Comment by alex-ter** [comment]
Ok, so I've double-checked it and I actually haven't tested it on that version, only 16.04. The problem there is that the `autoconf-archive` package version is reqlly old (2013) and `AX_REQUIRE_DEFINED` macro we use was added in 2014. I'm going to fix this properly, but a bit later - ran out of time today. You can do the following as a workaround:
1. In your Tomboy git clone create a directory called `m4` or just `cd` to it if it's already created
1. Download the macro from [here](https://www.gnu.org/software/autoconf-archive/ax_require_defined.html) and save it as `ax_require_defined.m4` file in that directory

After that you'll run into what #9 is about (they apply several distro-specific patches for Tomboy in Debian/Ubuntu). Just apply [this change](https://anonscm.debian.org/cgit/pkg-cli-apps/packages/tomboy.git/tree/debian/patches/use_dbussharp_2.patch?id=f8ca6798b5fad70a8ce46c3f1565b2ab2f5485b6) to Tomboy's code and run `autogen.sh` again, it should pass, if not - please post the full log here.

**Comment by alex-ter** [comment]
I'm preparing fixes for committing for both of these, but there seems to be some further problem with 14.04 (16.04 is ok with just #9 addressed). I'm looking into this.

**Comment by alex-ter** [comment]
All commits necessary to build on Ubuntu 14 are in the repo now, feel free to give it a try and report back if any problems arise.

Please note that you cannot run `make distcheck` right after running `autogen.sh` on Ubuntu 14 due to the fact another package - `yelp-tools` - is also quite old there and contains a certain [bug](https://github.com/GNOME/yelp-tools/commit/d18d4ff5cb67a07977aa9957fe82322b22380ef3). You need to run `make` before running `make distcheck` for it to work (or get newer `yelp-tools`). However this specific target is gnerally useful only for package maintainers, so shouldn't affect you at all, putting it here just to document. I'll also add this to the build-related wiki page.
