### ISSUE TITLE
search highlight color produces low contrast, should be customizable [includes proposed patch]

### ISSUE THREAD

**Issue by acrothoi2** [tomboy-notes/tomboy#33]
(Copied from https://bugzilla.gnome.org/show_bug.cgi?id=748661) ...

Julie:
> The search highlight color is dark green, which does not contrast well with black text (which is probably the color of text for most users).
> 
> Attaching screen capture illustrating the problem.

> the second instance of "search string" demonstrates the problem -- dark green highlighting of dark black text
![search-highlight](https://cloud.githubusercontent.com/assets/24640690/21939921/ff4c724a-d98f-11e6-8b3c-c0c120ebe05c.png)

> The default should probably be changed to a much lighter color. Alternatively, or additionally, this should be customizable by the user in case their theme uses different text and background colors.

Alexander:
> I took it upon me to actually implement configurable highlight color for myself. If the patch would be of any interest to you I welcome any suggestions for improvement. I am actually trying to pick up C#, and this patch was my first try at it.

> highlight ui image
![tomboy_highlight_proposal](https://cloud.githubusercontent.com/assets/24640690/21940177/1ef94202-d991-11e6-90e3-efe47b16fb6b.png)

> proposed patch to allow configurable highlight color
https://bugzilla.gnome.org/attachment.cgi?id=308042&action=diff

**Comment by davidbannon** [comment]
I'd like support this enhancement. I have always found the excessive contrast in searched for terms offensive to the eye.

**Comment by alex-ter** [comment]
I've looked into this and I think this is mostly an issue for Linux, where "green" used by default is quite dark. On Windows that's not the case and it's more like "lawngreen" or "lime" (see [here](https://drafts.csswg.org/css-color/#named-colors)) already.

But I agree a degree of configurability would be nice in any case. The proposed patch has a couple of issues, so needs to be reworked before I can merge it. I'll ask whether the contributor is willing to rework it.

In the meanwhile, to make one step forward, I'll just implement the first part of the initial ask - i.e. set the search match color to "lawngreen", which is lighter and looks quite ok for me and well within what's being asked.

**Comment by alex-ter** [comment]
Ok, so the reference commit changes the default color and it now looks similar to Windows (Win itself is unchanged):
![image](https://cloud.githubusercontent.com/assets/5199601/21963365/df53c280-db39-11e6-8ca0-5408bdf59e59.png)

**Comment by acrothoi2** [comment]
definitely an improvement over the dark green. thanks! :-)

**Comment by alex-ter** [comment]
JFYI, I have the code, tested and almost ready to go in the https://github.com/tomboy-notes/tomboy/tree/gh33-add-custom-search-match-color branch, plan to get it in sometime this week. If anyone is eager to get the functionality as soon as possible and is up to building stuff - feel free to pick it up right away :smiley:
