### ISSUE TITLE
gtk-sharp 2.12.42 causes crash somewhere around Mono.Addins when loading plugins

### ISSUE THREAD

**Issue by alex-ter** [tomboy-notes/tomboy#34]
Just noticed that when working on bgo624002. Maybe our copy of Mono* DLLs is too old and needs updating.

Version 2.12.38 works ok though.

**As a workaround**, please do not use any newer GTK# versions available for download on the Mono website. Version 2.12.38 is still available (though not listed) for download using this direct link: https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.38.msi.

I'm also attaching a downloaded file just in case they remove it. You need to remove the ".txt" extension and leave only the ".msi" one, that was added because GitHub does not allow me to attach an MSI or even MSI in a ZIP file.

[gtk-sharp-2.12.38.msi.txt](https://github.com/tomboy-notes/tomboy/files/724917/gtk-sharp-2.12.38.msi.txt)

The exception looks like this:
```
[INFO 21:05:19.205] Initializing Mono.Addins
[DEBUG 21:05:19.252] AddinManager.OnAddinLoaded: Tomboy.Tomboy
[DEBUG 21:05:19.256]           Name: Tomboy.Tomboy,0.10
[DEBUG 21:05:19.257]    Description:
[DEBUG 21:05:19.257]      Namespace: Tomboy
[DEBUG 21:05:19.259]        Enabled: True
[DEBUG 21:05:19.260]           File: C:\MyDocs\dev\tomboy\tomboy-github\bin\Debug\Tomboy.exe
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   w System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   w Mono.Addins.AddinSessionService.CheckHostAssembly(Assembly asm)
   w Mono.Addins.AddinSessionService.ActivateRoots()
   w Mono.Addins.AddinSessionService.Initialize()
   w Mono.Addins.AddinManager.Initialize(String configDir)
   w Tomboy.AddinManager.InitializeMonoAddins(String old_conf_dir) w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\AddinManager.cs:line 93
   w Tomboy.AddinManager..ctor(String tomboy_conf_dir, String old_tomboy_conf_dir) w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\AddinManager.cs:line 45
   w Tomboy.NoteManager.Initialize() w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\NoteManager.cs:line 138
   w Tomboy.Tomboy.<>c__DisplayClass11_0.<Main>b__0() w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 101
   w GLib.Timeout.TimeoutProxy.Handler(IntPtr data)
   w GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   w GLib.Timeout.TimeoutProxy.Handler(IntPtr data)
   w Gtk.Application.gtk_main()
   w Tomboy.WindowsApplication.StartMainLoop() w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\WindowsApplication.cs:line 87
   w Tomboy.Tomboy.StartTrayIcon() w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 200
   w Tomboy.Tomboy.Main(String[] args) w C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 158
```

**Comment by alex-ter** [comment]
Added a note to the installation wiki page linking to this issue - the note should be removed when the issue is fixed: https://wiki.gnome.org/Apps/Tomboy/Installing/Windows

**Comment by alex-ter** [comment]
I've prepared an MSI with the fixed version, which contains newer Mono.Addins: https://github.com/tomboy-notes/tomboy/releases/tag/1.15.7-rc1.

Per my initial testing, everything works fine, however I'd be grateful for some testing help, to make sure we check it out in various environments before a full release.

As usual, it would make sense to backup your notes before testing, or using a clean VM or something similar. The only visible side effect I've noticed is that enabled/disabled add-in list got reset to default, however addin preferences themselves are untouched.

@stevedipaola, if you're up to that testing, feedback from you would be quite valuable, as you've had the same issue in #37.

**Comment by stevedipaola** [comment]
sorry swamped with other things, and am not currently using tomboy after a
quick initial look. Might get back to it later - but back to evernote
(which has a cheap wikiwords linking trick I use) for my notes/todo for the
short term, for a bit at least.

-  Steve DiPaola    -  -
 - Assoc. Professor, Simon Fraser University,
 - School: Interactive Arts & Technology + Program: Cognitive Science
    - - -  home:          www.dipaola.org
      - -  research:     http://ivizlab.sfu.ca/research
        -  art gallery:    www.dipaola.org/gallery

On Sat, Jan 28, 2017 at 12:26 PM, Alex Tereschenko <notifications@github.com

**Comment by alex-ter** [comment]
No worries, thanks for letting me know.

**Comment by alex-ter** [comment]
Ok, as there are no problems coming up in my tests and I haven't heard from anyone here - I'm moving on with the use of new Mono.Addins to fix the original issue.
