### ISSUE TITLE
moving text via drag-dropping text yields 3 odd characters (linux)

### ISSUE THREAD

**Issue by ghost** [tomboy-notes/tomboy#4]
Hi.

In a note, I select a bunch of text(could be a word or a line) then I attempt to move it with the mouse via drag and drop, in the same note or in another note and when I release the click, the following is pasted instead:

```
�
�
```

what looks like 3 characters(to me, but not here in github) separated by a new line.
The original selected text is not changed or deleted.

I'm using linux manjaro 64bit with xfce4 ...
**EDIT:**
$ tomboy --version
Tomboy: A simple, easy to use desktop note-taking application.
Copyright © 2004-2007 Alex Graveley
<alex@beatniksoftware.com>

Copyright © 2004-2011 Others
Version 1.14.1
under linux manjaro 64bit with xfce4
Linux manji 3.12.20-1-MANJARO #1 SMP PREEMPT Tue May 20 16:54:28 EST 2014 x86_64 GNU/Linux

**Comment by alex-ter** [comment]
@ghost, I'm doing some bug scrubbing, is this still actual for you?

**Comment by alex-ter** [comment]
Ok, apparently "ghost" is a substitute account for deleted users :smiley: so I'm closing this one, if anyone faces this - please post here and I'll reopen it.
