### ISSUE TITLE
Will not start windows 10

### ISSUE THREAD

**Issue by mash369** [tomboy-notes/tomboy#41]
I have installed tomboy for windows using the instructions and everything went well but when I start tomboy all a see is the icon in the taskbar for about 5 seconds but the program does not launch.

What have I done wrong?

Regards

Chris

**Comment by alex-ter** [comment]
Could you please post your Tomboy log, after starting it with the "--debug" command-line parameter?

**Comment by alex-ter** [comment]
@mash369, is this still actual?

**Comment by alex-ter** [comment]
Closing for no response, feel free to add comments if anyone else sees that.
