### ISSUE TITLE
Note Placement Doesn't Use Full Screen Width

### ISSUE THREAD

**Issue by JBHoren** [tomboy-notes/tomboy#43]
xdpyinfo confirms my monitor's screen dimensions as 1920x1080, and I can manually position notes throughout the full width and height. However, when I restart the application, the right-most column of notes _(see attached graphic)_ are positioned such that they overlap the notes in the second-from-right column.

xwininfo lists their "Absolute upper-left X" as 1371; this, together with the geometry (width) of 450, gives a right "margin" of 1821 -- 99 pixels short of the full 1920.

xwininfo also identifies the MATE Panel ("Top Expanded Edge Panel") as having a geometry of 1920x26+0+0, so the full width of the screen is available.

Every time I boot my workstation and/or log-in (Linux Mint 18.1 MATE) I'm forced to reposition these notes. Is this a bug, or a feature? In either case, is there a solution for this problem (other than manually moving them)?

![screenshot at 2017-03-16 23-18-50](https://cloud.githubusercontent.com/assets/26473006/24027650/82c72b48-0a9f-11e7-9f33-0f1820d0bd4d.png)

**Comment by alex-ter** [comment]
Could you please run tomboy with the "--debug" command-line option and post the log here? There should be messages, at least partially covering tomboy's "thought process" of restoring their placement.

**Comment by JBHoren** [comment]
body p { margin-bottom: 12pt; margin-top: 0pt; } 
  
  
    On 03/17/2017 07:57 AM, Alex
      Tereschenko wrote:
    
    
      Could you please run tomboy with the "--debug" command-line
        option and post the log here? There should be messages, at least
        partially covering tomboy's "thought process" of restoring their
        placement.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tomboy-notes/tomboy","title":"tomboy-notes/tomboy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tomboy-notes/tomboy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alex-ter in #43: Could you please run tomboy with the \"--debug\" command-line option and post the log here? There should be messages, at least partially covering tomboy's \"thought process\" of restoring their placement."}],"action":{"name":"View Issue","url":"https://github.com/tomboy-notes/tomboy/issues/43#issuecomment-287336084"}}}
    
    
    horen@elf ~ $ tomboy --debug
        ** Running Mono with --debug    **
        [DEBUG 07:59:59.790] NoteManager created with note path
        "/home/horen/.local/share/tomboy".
        [INFO 08:00:00.362] Initializing Mono.Addins
        [DEBUG 08:00:00.645] AddinManager.OnAddinLoaded: Tomboy.Tomboy
        [DEBUG 08:00:00.647]            Name: Tomboy.Tomboy,0.10
        [DEBUG 08:00:00.647]     Description: 
        [DEBUG 08:00:00.648]       Namespace: Tomboy
        [DEBUG 08:00:00.648]         Enabled: True
        [DEBUG 08:00:00.649]            File: /usr/lib/tomboy/Tomboy.exe
        [DEBUG 08:00:02.210] AddinManager.OnAddinLoaded:
        Tomboy.ExportToHtmlAddin
        [DEBUG 08:00:02.211]            Name: Export to HTML
        [DEBUG 08:00:02.211]     Description: Exports individual notes
        to HTML.
        [DEBUG 08:00:02.211]       Namespace: Tomboy
        [DEBUG 08:00:02.212]         Enabled: True
        [DEBUG 08:00:02.212]            File:
        /usr/lib/tomboy/addins/ExportToHtml.dll
        [DEBUG 08:00:02.218] AddinManager.OnAddinLoaded:
        Tomboy.WebSyncServiceAddin
        [DEBUG 08:00:02.219]            Name: Web Sync Service Add-in
        [DEBUG 08:00:02.219]     Description: Synchronize Tomboy Notes
        with Tomboy Online and other compatible web services
        [DEBUG 08:00:02.220]       Namespace: Tomboy
        [DEBUG 08:00:02.220]         Enabled: True
        [DEBUG 08:00:02.220]            File:
        /usr/lib/tomboy/addins/WebSyncServiceAddin.dll
        [DEBUG 08:00:02.222] AddinManager.OnAddinLoaded:
        Tomboy.FileSystemSyncServiceAddin
        [DEBUG 08:00:02.223]            Name: Local Directory Sync
        Service Add-in
        [DEBUG 08:00:02.224]     Description: Synchronize Tomboy Notes
        to a local file system path
        [DEBUG 08:00:02.224]       Namespace: Tomboy
        [DEBUG 08:00:02.224]         Enabled: True
        [DEBUG 08:00:02.225]            File:
        /usr/lib/tomboy/addins/FileSystemSyncService.dll
        [DEBUG 08:00:02.228] AddinManager.OnAddinLoaded:
        Tomboy.SshSyncServiceAddin
        [DEBUG 08:00:02.229]            Name: SSH Sync Service Add-in
        [DEBUG 08:00:02.229]     Description: Synchronize Tomboy Notes
        to a SSH share
        [DEBUG 08:00:02.230]       Namespace: Tomboy
        [DEBUG 08:00:02.230]         Enabled: True
        [DEBUG 08:00:02.230]            File:
        /usr/lib/tomboy/addins/SshSyncServiceAddin.dll
        [DEBUG 08:00:02.235] Unable to locate 'gnomesu' in your PATH
        [DEBUG 08:00:02.235] Using '/usr/bin/gksu' as GUI 'su' tool
        [DEBUG 08:00:02.236] Successfully found all system tools
        [DEBUG 08:00:02.236] Unable to locate 'sshfs' in your PATH
        [DEBUG 08:00:02.237] AddinManager.OnAddinLoaded:
        Tomboy.WebDavSyncServiceAddin
        [DEBUG 08:00:02.238]            Name: WebDav Sync Service Add-in
        [DEBUG 08:00:02.238]     Description: Synchronize Tomboy Notes
        to a WebDav URL
        [DEBUG 08:00:02.239]       Namespace: Tomboy
        [DEBUG 08:00:02.239]         Enabled: True
        [DEBUG 08:00:02.239]            File:
        /usr/lib/tomboy/addins/WebDavSyncService.dll
        [DEBUG 08:00:02.245] Unable to locate 'wdfs' in your PATH
        [DEBUG 08:00:02.278] Loading notes
        [DEBUG 08:00:02.670] AddinManager.OnAddinLoaded:
        Tomboy.UnderlineAddin
        [DEBUG 08:00:02.671]            Name: Underline
        [DEBUG 08:00:02.671]     Description: Adds ability to underline
        text.
        [DEBUG 08:00:02.671]       Namespace: Tomboy
        [DEBUG 08:00:02.671]         Enabled: True
        [DEBUG 08:00:02.672]            File:
        /usr/lib/tomboy/addins/Underline.dll
        [DEBUG 08:00:02.674] AddinManager.OnAddinLoaded:
        Tomboy.FixedWidthAddin
        [DEBUG 08:00:02.675]            Name: Fixed Width
        [DEBUG 08:00:02.675]     Description: Adds fixed-width font
        style.
        [DEBUG 08:00:02.675]       Namespace: Tomboy
        [DEBUG 08:00:02.676]         Enabled: True
        [DEBUG 08:00:02.676]            File:
        /usr/lib/tomboy/addins/FixedWidth.dll
        [DEBUG 08:00:02.679] AddinManager.OnAddinLoaded:
        Tomboy.StickyNoteImportAddin
        [DEBUG 08:00:02.679]            Name: Sticky Notes Importer
        [DEBUG 08:00:02.680]     Description: Import your notes from the
        Sticky Notes applet.
        [DEBUG 08:00:02.680]       Namespace: Tomboy
        [DEBUG 08:00:02.680]         Enabled: True
        [DEBUG 08:00:02.680]            File:
        /usr/lib/tomboy/addins/StickyNoteImport.dll
        [DEBUG 08:00:02.685] StickyNoteImporter: Sticky Notes XML file
        does not exist or is invalid!
        [DEBUG 08:00:02.687] AddinManager.OnAddinLoaded:
        Tomboy.PrintNotesAddin
        [DEBUG 08:00:02.687]            Name: Printing Support
        [DEBUG 08:00:02.688]     Description: Allows you to print a
        note.
        [DEBUG 08:00:02.688]       Namespace: Tomboy
        [DEBUG 08:00:02.688]         Enabled: True
        [DEBUG 08:00:02.688]            File:
        /usr/lib/tomboy/addins/PrintNotes.dll
        [DEBUG 08:00:02.690] AddinManager.OnAddinLoaded:
        Tomboy.BacklinksAddin
        [DEBUG 08:00:02.691]            Name: Backlinks
        [DEBUG 08:00:02.691]     Description: See which notes link to
        the one you're currently viewing.
        [DEBUG 08:00:02.691]       Namespace: Tomboy
        [DEBUG 08:00:02.691]         Enabled: True
        [DEBUG 08:00:02.692]            File:
        /usr/lib/tomboy/addins/Backlinks.dll
        [DEBUG 08:00:02.750] Creating Buffer for 'Bianchi Volpe'...
        [DEBUG 08:00:03.119] Bianchi Volpe tags:
        [DEBUG 08:00:03.280] Creating Buffer for 'Household Tasks'...
        [DEBUG 08:00:03.356] Household Tasks tags:
        [DEBUG 08:00:03.456] Creating Buffer for 'Income 2017'...
        [DEBUG 08:00:03.613] Income 2017 tags:
        [DEBUG 08:00:03.735] Creating Buffer for 'Farmers Market'...
        [DEBUG 08:00:03.883] Farmers Market tags:
        [DEBUG 08:00:03.996] Creating Buffer for 'Publix'...
        [DEBUG 08:00:04.198] Publix tags:
        [DEBUG 08:00:04.205]     system:notebook:Income/Budget
        [DEBUG 08:00:04.317] Creating Buffer for 'Target/HD/Walmart'...
        [DEBUG 08:00:04.460] Target/HD/Walmart tags:
        [DEBUG 08:00:04.461]     system:notebook:Income/Budget
        [DEBUG 08:00:04.566] Creating Buffer for 'Budget 2017'...
        [DEBUG 08:00:04.759] Budget 2017 tags:
        [DEBUG 08:00:04.862] Loading notebooks
        [DEBUG 08:00:04.991] Unable to locate 'sshfs' in your PATH
        [DEBUG 08:00:04.995] Unable to locate 'wdfs' in your PATH
        [DEBUG 08:00:05.043] Autosync pref changed...restarting sync
        timer
        [DEBUG 08:00:05.178] Tomboy remote control active.
        [DEBUG 08:00:07.291] Saving 'Bianchi Volpe'...
        [DEBUG 08:00:07.458] Saving 'Household Tasks'...
        [DEBUG 08:00:07.735] Saving 'Income 2017'...
        [DEBUG 08:00:07.996] Saving 'Farmers Market'...
        [DEBUG 08:00:08.317] Saving 'Publix'...
        [DEBUG 08:00:08.567] Saving 'Target/HD/Walmart'...
        [DEBUG 08:00:08.857] Saving 'Budget 2017'...
    [now exiting Tomboy]
    [INFO 08:00:59.309]
      Monitor number returned by GetMonitorAtPoint (actual) is: 0
      [INFO 08:00:59.310] Saved monitor number is: 0
      [INFO 08:00:59.310] Saved Search window position is 554 x 173
      [INFO 08:00:59.311] Saved monitor number does match the actual
      one...
      [INFO 08:00:59.311] ...and saved window position is within it -
      restoring as-is.
      [INFO 08:00:59.312] Restoring Search window to position 554 x 173
      at monitor 0
      [DEBUG 08:01:03.643] Quitting Tomboy.  Ciao!
      [DEBUG 08:01:03.650] Saving unsaved notes...
      horen@elf ~ $

**Comment by JBHoren** [comment]
On 03/17/2017 07:57 AM, Alex Tereschenko wrote:
>
> Could you please run tomboy with the "--debug" command-line option and post the log here? There should be messages, at least partially covering tomboy's "thought process" of restoring their placement.

horen@elf ~ $ tomboy --debug
** Running Mono with --debug    **
[DEBUG 07:59:59.790] NoteManager created with note path "/home/horen/.local/share/tomboy".
[INFO 08:00:00.362] Initializing Mono.Addins
[DEBUG 08:00:00.645] AddinManager.OnAddinLoaded: Tomboy.Tomboy
[DEBUG 08:00:00.647]            Name: Tomboy.Tomboy,0.10
[DEBUG 08:00:00.647]     Description:
[DEBUG 08:00:00.648]       Namespace: Tomboy
[DEBUG 08:00:00.648]         Enabled: True
[DEBUG 08:00:00.649]            File: /usr/lib/tomboy/Tomboy.exe
[DEBUG 08:00:02.210] AddinManager.OnAddinLoaded: Tomboy.ExportToHtmlAddin
[DEBUG 08:00:02.211]            Name: Export to HTML
[DEBUG 08:00:02.211]     Description: Exports individual notes to HTML.
[DEBUG 08:00:02.211]       Namespace: Tomboy
[DEBUG 08:00:02.212]         Enabled: True
[DEBUG 08:00:02.212]            File: /usr/lib/tomboy/addins/ExportToHtml.dll
[DEBUG 08:00:02.218] AddinManager.OnAddinLoaded: Tomboy.WebSyncServiceAddin
[DEBUG 08:00:02.219]            Name: Web Sync Service Add-in
[DEBUG 08:00:02.219]     Description: Synchronize Tomboy Notes with Tomboy Online and other compatible web services
[DEBUG 08:00:02.220]       Namespace: Tomboy
[DEBUG 08:00:02.220]         Enabled: True
[DEBUG 08:00:02.220]            File: /usr/lib/tomboy/addins/WebSyncServiceAddin.dll
[DEBUG 08:00:02.222] AddinManager.OnAddinLoaded: Tomboy.FileSystemSyncServiceAddin
[DEBUG 08:00:02.223]            Name: Local Directory Sync Service Add-in
[DEBUG 08:00:02.224]     Description: Synchronize Tomboy Notes to a local file system path
[DEBUG 08:00:02.224]       Namespace: Tomboy
[DEBUG 08:00:02.224]         Enabled: True
[DEBUG 08:00:02.225]            File: /usr/lib/tomboy/addins/FileSystemSyncService.dll
[DEBUG 08:00:02.228] AddinManager.OnAddinLoaded: Tomboy.SshSyncServiceAddin
[DEBUG 08:00:02.229]            Name: SSH Sync Service Add-in
[DEBUG 08:00:02.229]     Description: Synchronize Tomboy Notes to a SSH share
[DEBUG 08:00:02.230]       Namespace: Tomboy
[DEBUG 08:00:02.230]         Enabled: True
[DEBUG 08:00:02.230]            File: /usr/lib/tomboy/addins/SshSyncServiceAddin.dll
[DEBUG 08:00:02.235] Unable to locate 'gnomesu' in your PATH
[DEBUG 08:00:02.235] Using '/usr/bin/gksu' as GUI 'su' tool
[DEBUG 08:00:02.236] Successfully found all system tools
[DEBUG 08:00:02.236] Unable to locate 'sshfs' in your PATH
[DEBUG 08:00:02.237] AddinManager.OnAddinLoaded: Tomboy.WebDavSyncServiceAddin
[DEBUG 08:00:02.238]            Name: WebDav Sync Service Add-in
[DEBUG 08:00:02.238]     Description: Synchronize Tomboy Notes to a WebDav URL
[DEBUG 08:00:02.239]       Namespace: Tomboy
[DEBUG 08:00:02.239]         Enabled: True
[DEBUG 08:00:02.239]            File: /usr/lib/tomboy/addins/WebDavSyncService.dll
[DEBUG 08:00:02.245] Unable to locate 'wdfs' in your PATH
[DEBUG 08:00:02.278] Loading notes
[DEBUG 08:00:02.670] AddinManager.OnAddinLoaded: Tomboy.UnderlineAddin
[DEBUG 08:00:02.671]            Name: Underline
[DEBUG 08:00:02.671]     Description: Adds ability to underline text.
[DEBUG 08:00:02.671]       Namespace: Tomboy
[DEBUG 08:00:02.671]         Enabled: True
[DEBUG 08:00:02.672]            File: /usr/lib/tomboy/addins/Underline.dll
[DEBUG 08:00:02.674] AddinManager.OnAddinLoaded: Tomboy.FixedWidthAddin
[DEBUG 08:00:02.675]            Name: Fixed Width
[DEBUG 08:00:02.675]     Description: Adds fixed-width font style.
[DEBUG 08:00:02.675]       Namespace: Tomboy
[DEBUG 08:00:02.676]         Enabled: True
[DEBUG 08:00:02.676]            File: /usr/lib/tomboy/addins/FixedWidth.dll
[DEBUG 08:00:02.679] AddinManager.OnAddinLoaded: Tomboy.StickyNoteImportAddin
[DEBUG 08:00:02.679]            Name: Sticky Notes Importer
[DEBUG 08:00:02.680]     Description: Import your notes from the Sticky Notes applet.
[DEBUG 08:00:02.680]       Namespace: Tomboy
[DEBUG 08:00:02.680]         Enabled: True
[DEBUG 08:00:02.680]            File: /usr/lib/tomboy/addins/StickyNoteImport.dll
[DEBUG 08:00:02.685] StickyNoteImporter: Sticky Notes XML file does not exist or is invalid!
[DEBUG 08:00:02.687] AddinManager.OnAddinLoaded: Tomboy.PrintNotesAddin
[DEBUG 08:00:02.687]            Name: Printing Support
[DEBUG 08:00:02.688]     Description: Allows you to print a note.
[DEBUG 08:00:02.688]       Namespace: Tomboy
[DEBUG 08:00:02.688]         Enabled: True
[DEBUG 08:00:02.688]            File: /usr/lib/tomboy/addins/PrintNotes.dll
[DEBUG 08:00:02.690] AddinManager.OnAddinLoaded: Tomboy.BacklinksAddin
[DEBUG 08:00:02.691]            Name: Backlinks
[DEBUG 08:00:02.691]     Description: See which notes link to the one you're currently viewing.
[DEBUG 08:00:02.691]       Namespace: Tomboy
[DEBUG 08:00:02.691]         Enabled: True
[DEBUG 08:00:02.692]            File: /usr/lib/tomboy/addins/Backlinks.dll
[DEBUG 08:00:02.750] Creating Buffer for 'Bianchi Volpe'...
[DEBUG 08:00:03.119] Bianchi Volpe tags:
[DEBUG 08:00:03.280] Creating Buffer for 'Household Tasks'...
[DEBUG 08:00:03.356] Household Tasks tags:
[DEBUG 08:00:03.456] Creating Buffer for 'Income 2017'...
[DEBUG 08:00:03.613] Income 2017 tags:
[DEBUG 08:00:03.735] Creating Buffer for 'Farmers Market'...
[DEBUG 08:00:03.883] Farmers Market tags:
[DEBUG 08:00:03.996] Creating Buffer for 'Publix'...
[DEBUG 08:00:04.198] Publix tags:
[DEBUG 08:00:04.205]     system:notebook:Income/Budget
[DEBUG 08:00:04.317] Creating Buffer for 'Target/HD/Walmart'...
[DEBUG 08:00:04.460] Target/HD/Walmart tags:
[DEBUG 08:00:04.461]     system:notebook:Income/Budget
[DEBUG 08:00:04.566] Creating Buffer for 'Budget 2017'...
[DEBUG 08:00:04.759] Budget 2017 tags:
[DEBUG 08:00:04.862] Loading notebooks
[DEBUG 08:00:04.991] Unable to locate 'sshfs' in your PATH
[DEBUG 08:00:04.995] Unable to locate 'wdfs' in your PATH
[DEBUG 08:00:05.043] Autosync pref changed...restarting sync timer
[DEBUG 08:00:05.178] Tomboy remote control active.
[DEBUG 08:00:07.291] Saving 'Bianchi Volpe'...
[DEBUG 08:00:07.458] Saving 'Household Tasks'...
[DEBUG 08:00:07.735] Saving 'Income 2017'...
[DEBUG 08:00:07.996] Saving 'Farmers Market'...
[DEBUG 08:00:08.317] Saving 'Publix'...
[DEBUG 08:00:08.567] Saving 'Target/HD/Walmart'...
[DEBUG 08:00:08.857] Saving 'Budget 2017'...

[now exiting Tomboy]

[INFO 08:00:59.309] Monitor number returned by GetMonitorAtPoint (actual) is: 0
[INFO 08:00:59.310] Saved monitor number is: 0
[INFO 08:00:59.310] Saved Search window position is 554 x 173
[INFO 08:00:59.311] Saved monitor number does match the actual one...
[INFO 08:00:59.311] ...and saved window position is within it - restoring as-is.
[INFO 08:00:59.312] Restoring Search window to position 554 x 173 at monitor 0
[DEBUG 08:01:03.643] Quitting Tomboy.  Ciao!
[DEBUG 08:01:03.650] Saving unsaved notes...
horen@elf ~ $

**Comment by JBHoren** [comment]
MISTAKE!!! I don't know how it happened (OK, obviously I clicked on the wrong button, lol). Anyway, please reopen this issue :)

**Comment by JBHoren** [comment]
The interface is confusing. "Comment" means just that, but "Close and comment" does NOT mean "close the comment and submit it" (as in "finish"). I'm not stupid, but the intent is not clear... to me, anyway. Sorry.

**Comment by alex-ter** [comment]
Ok, thanks. Unfortunately not as much as I've hoped for, so some source code research is in order, which will take me a while to get to, so if anyone's willing to step in and take a look - be my guest.

**Comment by JBHoren** [comment]
I'm outta here. In general, I decided to leave Linux Mint 18/19 with the full MATE DE and opted for minimal installations (netinstall) of Ubuntu Bionic and Cosmic, both launching X11 desktops via XDM and running the JWM/Xcompmgr combo. And Tomboy? Bye-bye. Replaced by its "next generation" application, Gnote.
