### ISSUE TITLE
Can't launch Tomboy

### ISSUE THREAD

**Issue by saigkill** [tomboy-notes/tomboy#44]
I try to launch tomboy on openSUSE. 
After launching in the terminal i'm getting:

> sascha@linux-ktr9:~/repos/osc/home:saigkill/usermode> tomboy 
> 
> Unhandled Exception:
> System.Exception: Unable to open the system message bus. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Method `org.freedesktop.DBus.IBusProxy:.ctor ()' is inaccessible from method `DBus.BusObject:.ctor ()'
> 
>   at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_throw_method_access (intptr,intptr)
>   at org.freedesktop.DBus.IBusProxy..ctor () [0x00000] in <1c2f3370a86940c5832628c01db991b7>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <f712f98eb8e445c8918edaf595bbe465>:0 
>    --- End of inner exception stack trace ---
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00019] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000ca] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x0001a] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x0002a] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00040] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.Activator.CreateInstance (System.Type type) [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at DBus.BusObject.GetObject (DBus.Connection conn, System.String bus_name, DBus.ObjectPath object_path, System.Type declType) [0x0000d] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Connection.GetObject (System.Type type, System.String bus_name, DBus.ObjectPath path) [0x00018] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Connection.GetObject[T] (System.String bus_name, DBus.ObjectPath path) [0x00001] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus..ctor (System.String address) [0x0000f] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus.Open (System.String address) [0x0002b] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus.get_System () [0x00035] in <575bb7b60f08428c802d1a213a60c317>:0 
>    --- End of inner exception stack trace ---
>   at DBus.Bus.get_System () [0x00052] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.BusG.Init () [0x00010] in <77085a3dc5f44644859067a8e615d3d2>:0 
>   at Tomboy.RemoteControlProxy.get_FirstInstance () [0x00011] in <414597a0b35c46da9da989a1d3ce30ec>:0 
>   at Tomboy.Tomboy.Main (System.String[] args) [0x00042] in <414597a0b35c46da9da989a1d3ce30ec>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Unable to open the system message bus. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Method `org.freedesktop.DBus.IBusProxy:.ctor ()' is inaccessible from method `DBus.BusObject:.ctor ()'
> 
>   at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_throw_method_access (intptr,intptr)
>   at org.freedesktop.DBus.IBusProxy..ctor () [0x00000] in <1c2f3370a86940c5832628c01db991b7>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <f712f98eb8e445c8918edaf595bbe465>:0 
>    --- End of inner exception stack trace ---
>   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00019] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000ca] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x0001a] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x0002a] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00040] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at System.Activator.CreateInstance (System.Type type) [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0 
>   at DBus.BusObject.GetObject (DBus.Connection conn, System.String bus_name, DBus.ObjectPath object_path, System.Type declType) [0x0000d] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Connection.GetObject (System.Type type, System.String bus_name, DBus.ObjectPath path) [0x00018] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Connection.GetObject[T] (System.String bus_name, DBus.ObjectPath path) [0x00001] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus..ctor (System.String address) [0x0000f] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus.Open (System.String address) [0x0002b] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.Bus.get_System () [0x00035] in <575bb7b60f08428c802d1a213a60c317>:0 
>    --- End of inner exception stack trace ---
>   at DBus.Bus.get_System () [0x00052] in <575bb7b60f08428c802d1a213a60c317>:0 
>   at DBus.BusG.Init () [0x00010] in <77085a3dc5f44644859067a8e615d3d2>:0 
>   at Tomboy.RemoteControlProxy.get_FirstInstance () [0x00011] in <414597a0b35c46da9da989a1d3ce30ec>:0 
>   at Tomboy.Tomboy.Main (System.String[] args) [0x00042] in <414597a0b35c46da9da989a1d3ce30ec>:0 
Maybe i miss any dependency?

**Comment by alex-ter** [comment]
Which exact openSUSE version and how did you install Tomboy?

**Comment by saigkill** [comment]
I'm using openSUSE Tumbleweed (Rolling Release) with AFAIK Gnome 3.22

**Comment by saigkill** [comment]
Got the error. I had installed a Tumbleweed with the additional mono repository on: http://www.mono-project.com/docs/getting-started/install/linux/#opensuse-and-sles
After removing and installing the default Tumbleweed packages Tomboy runs again :-)
So i can close the issue.

**Comment by alex-ter** [comment]
Interesting, thanks for reporting back! Do you by any chance have the package reinstall log? I wonder what was the difference between working and non-working ones.
