### ISSUE TITLE
Pressing Escape on deletion confirmation dialog deletes category

### ISSUE THREAD

**Issue by d-damien** [tomboy-notes/tomboy#47]
And that's counter-intuitive. Happens only with categories.

- Tomboy 1.15.4
- Linuxmint 17.1

**Comment by alex-ter** [comment]
Could you please elaborate on "categories", what do you mean by that?

**Comment by d-damien** [comment]
Not sure how it is written in english versions − notepads, notebooks ? The "folders" in the sidebar to help you sort your notes.

**Comment by alex-ter** [comment]
I see, thanks. Yes, these are called notebooks in the English version.

So you mean when deleting notes Escape works as expected and cancels the deletion dialog, while when you do the same with notebooks, it causes the dialog to close and execute like if you clicked "ok/yes", do I get it right?

**Comment by d-damien** [comment]
Yes, exactly.

**Comment by alex-ter** [comment]
Understood and confirmed - that's due to the suboptimal keyboard accelerator registration logic in our custom dialogs. I've fixed that and will push in a minute. You'll need to submit a ticket to your distro maintainers to pick the new Tomboy version - the one you have right now is a bit old.

**Comment by d-damien** [comment]
Thank you !

**Comment by alex-ter** [comment]
My pleasure :-)
