### ISSUE TITLE
crashes? after deleting a note?

### ISSUE THREAD

**Issue by qptain-Nemo** [tomboy-notes/tomboy#49]
Tomboy has reached the state where if I launch it with "tomboy --search" and close the search window the whole program crashes (or exits silently?). There is no output in the terminal when that happens. Launching it without "--search" parameter from the terminal doesn't result in this behavior, but when launched from an xfce launcher it does 

And actually, subsequent testing has intermittent results that sometimes contradict what I just outlined. 

What I've done previously is delete a note form the "unfiled notes" view, then when tomboy windows stopped being closeable (behavior I've encountered before when I placed tomboy windows on different xfce4 workspaces, but that's another matter) I decided to restart it and ran into this situation. I wish I could provide more specifics, but that doesn't seem possible.

I'm using Arch Linux and xfce.

**Comment by alex-ter** [comment]
Let's add "--debug" to your command line, that would provide more information on the console and in the log file.

**Comment by qptain-Nemo** [comment]
After a series of restarts the issue has disappeared and I can't seem to reproduce it. Perhaps I should've saved the state of the tomboy directory when the issue manifested but I didn't think of that at the moment. I'm sorry. If it occurs again, I know what to do at least.

**Comment by alex-ter** [comment]
No worries and thanks for reporting back. Feel free to submit a new one, or just update this one if this happens again.
