### ISSUE TITLE
New installation on Windows 10 not working

### ISSUE THREAD

**Issue by V-Haring** [tomboy-notes/tomboy#57]
Just came across Tomboy and wanted to give it a go on my Windows 10 notebook. The instructions on your web site were followed for the installation. Although I was not asked to reboot the computer, I did it anyway for good measure. As the desktop icon failed to start the program, I tried it from a terminal and get the following output:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Gtk.IconTheme.gtk_icon_theme_load_icon(IntPtr raw, IntPtr icon_name, Int32 size, Int32 flags, IntPtr& error)
   at Gtk.IconTheme.LoadIcon(String icon_name, Int32 size, IconLookupFlags flags)
   at Tomboy.GuiUtils.GetIcon(Assembly asm, String resource_name, Int32 size) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 145
   at Tomboy.ActionManager..ctor() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\ActionManager.cs:line 52
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1070
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82
```

The GTK libs are in the path:
```
c:\utils\Tomboy>path
PATH=...C:\utils\GTK2-Runtime\bin;C:\Utils\GtkSharp\2.12\bin;...

```
I thought it might be the GTK installations (got the files from the instruction links) and definitely got GTK# for .NET and not for Mono. Changing the path statements (removing "\bin") only resulted in a missing dll error.

The Installation files used (and order in which installed):
- gtk2-runtime-2.24.10-2012-10-10-ash.exe
- gtk-sharp-2.12.44.msi (for .NET)
- Tomboy-1.15.9.msi

Any obvious error I made during the installation? Is there an easy fix for this? 
Thanks

**Comment by alex-ter** [comment]
That looks like it's not able to load one of the icons when initializing the app, but there's no known issues with this. Could you please start the app from console using --debug switch and post a full log? I'm away from my dev machine right now (and for about a week more), but I'll look into that afterwards. Or someone else may chime in.  The installation steps you've described look ok to me, so that must be something else.

**Comment by alex-ter** [comment]
@V-Haring, could you please provide the full log?

**Comment by V-Haring** [comment]
Thanks alex-ter for following this up.
The "full" log is included in my initial email. I just started the app again with the --debug switch and this is what I got:
`
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Gtk.IconTheme.gtk_icon_theme_load_icon(IntPtr raw, IntPtr icon_name, Int32 size, Int32 flags, IntPtr& error)
   at Gtk.IconTheme.LoadIcon(String icon_name, Int32 size, IconLookupFlags flags)
   at Tomboy.GuiUtils.GetIcon(Assembly asm, String resource_name, Int32 size) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 145
   at Tomboy.ActionManager..ctor() in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\ActionManager.cs:line 52
   at Tomboy.Application.Initialize(String locale_dir, String display_name, String process_name, String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Utils.cs:line 1070
   at Tomboy.Tomboy.Main(String[] args) in C:\MyDocs\dev\tomboy\tomboy-github\Tomboy\Tomboy.cs:line 82
`
Also checked the installation folder for any log files but could not find any.

**Comment by V-Haring** [comment]
Sorry, accidentally closed the issue; still trying to find my way around Github

**Comment by alex-ter** [comment]
I see, it just looked to me like a log excerpt and not the full one - usually there's more data, but I think in your case it's just that it happens very early in the application initialization process.

I've just tested on my Win10 test VM, with GTK# and Tomboy updated to the same versions you have, cannot reproduce the issue. I'm trying a couple of other things right now, but could you please help me with the following information:
1. Tomboy log file (it's unlikely to contain anything else than you posted, but let's see) - it's located in `%LOCALAPPDATA%\Tomboy\tomboy.log`
1. Please check if you have the `C:\utils\Tomboy\share\icons\hicolor\16x16\actions` folder and a `note-new.png` file inside it.
1. Is you user account a member of the Administrators group, or just a Users-level one?

**Comment by alex-ter** [comment]
I've tried installing Tomboy to a non-default path, like you have and running it as a Users-level account, none of that gives a reproduction. So I'm bit out of ideas for now, the only other thing I have left to try is updating the VM to the latest Win10 patchset (I haven't powered it on for a while), but in general that's unlikely to change the OS behavior that drastically, we'll see.

In the meanwhile, please check those things I've asked about in my previous comment, maybe we could get some clues out of that.

**Comment by V-Haring** [comment]
Hi Alex,
here is the requested info:
1. the log file is empty. I tried to run tomboy again with and without the --debug switch, but the log file remains empty.
2. yes, the action folder contains `note-new.png`
3. my user account is part of the Admin group.

Regards to your second comment, I recently got the latest Windows updates. These cause me now some issues with my power and WiFi settings, which are now often, but not always ignored. I don't know if this is of any relevance, but I thought I should mention it.

Hope this helps in some way,
Volker

**Comment by alex-ter** [comment]
Thanks. After some more searching I see this may be a DLL clash somewhere, something I vaguely suspected. See [this](http://gnome-tomboy.1788872.n4.nabble.com/Crash-at-startup-on-Vista-td1790825.html) email thread. Could you please try that ListDLL thing (see email from Sandy Armstrong of June 24th) to see where the clas may be?

**Comment by V-Haring** [comment]
Here is the output from `listdlls tomboy > dlls-tomboy.txt` (run with elevated privileges, just in case).  
[dlls-tomboy.txt](https://github.com/tomboy-notes/tomboy/files/1213361/dlls-tomboy.txt)

**Comment by alex-ter** [comment]
Thanks. So there indeed seems to a clash - this thing, "C:\Program Files (x86)\IDM Computer Solutions\UltraCompare\zlib1.dll" apparently shouldn't be there and it overrides the same library from GTK+,  causing problems. Please check if any parts of this path are located in PATH an try moving that somewhere after GTK+ path, or remove it completely (temporarily, just for test).

**Comment by alex-ter** [comment]
@V-Haring, have you beenableto try the above? I'm pretty sure this is the reason and as you can see it has nothgin to do with Tomboy itself, so I don't think I'll be able to help any further with this.

**Comment by V-Haring** [comment]
Hi Alex,
Sorry for the late reply, I was on the road last week without my computer.

I moved the "offending" reference the bottom of the path and the the GTK references higher up. Now Tomboy starts, although it looks a bit "distorted". It is quite workable, but I don't think it looks like as it should. There are a few warnings showing up with the --debug options
`[WARN 13:12:27.897] Preference key '/apps/tomboy/global_keybindings/show_note_menu' does not exist, using default.
[DEBUG 13:12:27.897] Binding key '<Alt>F12' for '/apps/tomboy/global_keybindings/show_note_menu'
[WARN 13:12:27.913] Preference key '/apps/tomboy/global_keybindings/open_start_here' does not exist, using default.
[DEBUG 13:12:27.913] Binding key '<Alt>F11' for '/apps/tomboy/global_keybindings/open_start_here'
[WARN 13:12:27.913] Preference key '/apps/tomboy/global_keybindings/open_search' does not exist, using default.
[DEBUG 13:12:27.975] Unable to load icon 'tomboy-panel'.
`
A full debug log and some screenshots are attached.
[Tomboy.zip](https://github.com/tomboy-notes/tomboy/files/1240816/Tomboy.zip)
This is probably a new issue and I'm happy to close this and open a new one.

Thanks a lot for your support, much appreciated
Volker

**Comment by alex-ter** [comment]
Good! Glad we've found the solution for the original issue :)

The distortion looks like somethiung completely else and those log warnings are harmless, it's just Tomboy creatign default values for some of the settings. I'd appreciate it if you could submit a new issue for this one, I'll start investigating in the meanwhile. The scrrenshots are very helpful, one more thing I'd need is - which Win10 version is that (bitness, edition)?
