### ISSUE TITLE
selecting text with numHome/numEnd keys doesn't work

### ISSUE THREAD

**Issue by ghost** [tomboy-notes/tomboy#6]
Hi.

I notice that using Shift+Home and Shift+End work: they select the text, but when using Shift+NumHome (shift+numkey7) and Shift+NumEnd (shift+numkey1) while numlock is on, just executes a normal Home or End action without also selecting the text. Note that when numlock if off, the system just pastes the number 7 or 1 (this happens in all the programs though). 
 In other programs (e.g. firefox) shift+numHome (ie. shift+numkey7) does select the text while doing a Home.

Thanks.

**EDIT:**
$ tomboy --version
Tomboy: A simple, easy to use desktop note-taking application.
Copyright © 2004-2007 Alex Graveley
<alex@beatniksoftware.com>

Copyright © 2004-2011 Others
Version 1.14.1
under linux manjaro 64bit with xfce4
Linux manji 3.12.20-1-MANJARO #1 SMP PREEMPT Tue May 20 16:54:28 EST 2014 x86_64 GNU/Linux

**Comment by alex-ter** [comment]
@ghost, I'm doing some bug scrubbing, is this still actual for you?

**Comment by alex-ter** [comment]
Ok, apparently "ghost" is a substitute account for deleted users :smiley: so I'm closing this one, if anyone faces this - please post here and I'll reopen it.
