### ISSUE TITLE
Need support for Tamil Language - Very Oldest and Famous Language

### ISSUE THREAD

**Issue by jkathir** [tomboy-notes/tomboy#65]
For tamil fonts, please go through the following steps

Download http://www.azhagi.com/ software which is the tamil editor like
microsoft word
Type the text in different font like choosing in microsoft word
You can see the font as well as the text
Make sure the text is being supported

Fonts for your kind reference:

http://www.azhagi.com/freefonts.html#top1
http://tamil.indiatyping.com/index.php/download-tamil-font
http://www.freetamilfont.com/

**Comment by alex-ter** [comment]
If you are talking about the interface - then Tamil is supported and 95% is translated: https://l10n.gnome.org/vertimus/tomboy/master/po/ta, if you want to increase the ration, you'd better get in touch with the GNOME L10N team (or just update the PO file yourself with POedit and file a pull request).

If you are talking about the note contents, then it all depends on your OS, Tomboy is a Unicode application and should support whatever you have, if .NET/Mono supports that.
